name: Continuous Delivery
on:
  push:
    branches:
      - main # ou qualquer outra branch
jobs:
  deliver: # nome
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: | # '**.py' todos arquivos python
            '**.py' #
            README.md